---
- name: Check if Claude Code is installed
  command: which claude
  register: claude_check
  failed_when: false
  changed_when: false

- name: Install Claude Code via npm
  shell: |
    export NVM_DIR="{{ home }}/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    npm install -g @anthropic-ai/claude-code
  args:
    executable: /bin/bash
  when: claude_check.rc != 0

- name: Create .claude directory
  file:
    path: "{{ home }}/.claude"
    state: directory
    mode: '0755'

- name: Copy Claude configuration files
  copy:
    src: "files/claude/"
    dest: "{{ home }}/.claude/"
    owner: "{{ user }}"
    mode: '0644'
  when: claude_files.stat.exists
  vars:
    claude_files:
      stat:
        exists: "{{ (playbook_dir + '/files/claude') | exists }}"

- name: Check for Claude files directory
  stat:
    path: "{{ playbook_dir }}/files/claude"
  register: claude_files_check

- name: Copy Claude configuration files if they exist
  copy:
    src: "{{ item }}"
    dest: "{{ home }}/.claude/"
    owner: "{{ user }}"
    mode: '0644'
  with_fileglob:
    - "files/claude/*"
  when: claude_files_check.stat.exists